#!/usr/bin/env ruby
#
# A demo of the format_output gem.
#

require_relative '..\lib\format_output'

# Some simple number, squared, and cubed columns
column_data = Array.new(25) { |i| "#{i}, #{i*i}, #{i*i*i}  " }
puts "Numbers, squares, and cubes.", ""
column_data.puts_format_output_columns(width: 72)
